### ISSUE TITLE
Documentation or function error?

### ISSUE THREAD

**Issue by clewisgithub** [clarson/Captcha-noCAPTCHA#2]
Version 0.6 noCAPTCHA

I have Captcha::reCAPTCHA working.  I'm trying to convert to noCAPTCHA to see if it works better in China.  reCAPTCHA doesn't work at all (doesn't even render).

noCAPTCHA documentation refers to CGI parameter g-captcha-response.  No such variable is returned.  Dumping param() shows it's g-recaptcha-response.

When you pass the g-recaptcha-response value to $captcha->verify, it always fails, even when you get the checkmark saying you passed.

Code:
# Your re)CAPTCHA keys from
# https://www.google.com/recaptcha/admin/create

use constant PUBLIC_KEY  => '6LeTZ_4SAAAAADqyAPbrf99YCO0x4fs4-CgKO7kG';
use constant PRIVATE_KEY => 'omitted';

(the above captcha keys work with regular Captcha::reCAPTCHA)
# Newer captcha

use Captcha::noCAPTCHA;

my $captcha = Captcha::noCAPTCHA->new(
        {site_key => PUBLIC_KEY,
         secret_key => PRIVATE_KEY,
         theme => 'dark'});

...

$capterror = 'none';
if ( $response = param( 'g-recaptcha-response' ) ) {
    $capterror = $captcha->verify( $response, $srcip ) ? 'passed': 'bad';
}

...

print
    start_form(-method=>'POST'),
    table(
        td( 'IP address: '),
        td(textfield(-name=>'ip', -size=>'15', -maxlength=>'15')),
        td($captcha->html),
        #td(submit(-name => '.pubmit', -value => 'Lookup')),
        td(image_button(-name => '.pubmit', -src => 'supp/lookup.gif', -alt => 'Lo
okup', -value => 'Lookup')),
    ),
    end_form();

....

if ($capterror ne 'passed') {
     exit cgi...
}

Do protected stuff.

**Comment by clarson** [comment]
Hi,

Yes, the documentation is incorrect and should be "g-recaptcha-response"  Documentation will be updated shortly on CPAN.  As to your issue with always failing, I copied your script and made it work wiith my keys and it worked just fine.  One suggestion is to try to access https://www.google.com/recaptcha/api/siteverify from your server to confirm access to google's web site.

Anothing to make sure is that  IO::Socket::SSL and Net::SSLeay are installed.  If not and you are not able to install it, you could try setting the api_url with plain http instead of https.

Thanks,
Chuck

**Comment by clewisgithub** [comment]
Hi Chuck,

Thanks for the ack on the docs.

I have Captcha::reCAPTCHA working in this very same script on the very
same machine and same keys.

I'd stick with that, but it doesn't work in China, and I was hoping that
_maybe_ noCAPTCHA would work, OR, could be made to sorta work.  At this
point I'd be happy if the noCAPTCHA implementation had some way of
telling me "the user couldn't access google" and not bother with
captcha.  My security problem isn't with China.

I simply copied that reCAPTCHA CGI to a different name in the same
directory and converted it to noCAPTCHA.  I had removed the use
"Captcha::reCAPTCHA", so, there shouldn't be any module confusion.

I try doing a wgets of the siteverify, and I get this:

{
  "success": false,
  "error-codes": [
    "missing-input-response",
    "missing-input-secret"
  ]
}

I get the same thing when I use my browser from home (not registered).

Yes, I could construct a verify url with the IP and the response etc.,
but that would already tell me what I know - these keys work from this
machine.  When I get the site key wrong, google replaces the nocaptcha
picture with "invalid site key".

It would go a long way to figuring out what's going on if you exposed a
method to get at the json returned from the verify.  Then I should be
able to distinguish different kind of failures.  Like: "request
timeout/no such route to host", whatever.  I'd owe you a beer if you got
me something that said that....

I suppose I can hack the library for debugging purposes, but a published
method for retrieving the json in text would be better.

Fudzing with http api_url didn't work.

**Comment by clewisgithub** [comment]
I hacked the library to dump stuff so I could see what's happening.

This is crazy.

Immediately after the call to post_form, I put:

open(X, '>/tmp/J');
print X 'uri:', $self->api_url, "\n";
print X 'parms: ', Dumper($params);
print X 'response: ', Dumper($response);
close(X);

Output - notice it does a 403 reject!  HTTP::Tiny and JSON::PP seem to
be up to date.

Thoughts?

uri:http://www.google.com/recaptcha/api/siteverify
parms: $VAR1 = {
          'response' =>
'03AHJ_VutRHAlFdhn_TmLZ1UD3BX9yfPENu7sIDobxbqRjI6D_qVBJ14DtU5eXa-cbFBCwSCwchSO06MZ2HIldR0faHRMwwge5ZPxdc67XKW8KTT6P25t4zXg07uNf_vqkdPtm58Viswpb8toMjHOEKdYuV7k5De5LU8eDq5omOBNdFV5zU_cpBDLvt6N1lbxYQT77CcmWTjIu2nRZRrRR_I-rw1PpNVkz3Vht-zGip9pqIiVhBB5hsI0dAMap0LrL_D8L2GZYnPlKWduvf1_wl579UFfAVnNvbooMXSY2Gl6oFUemXzDGbwfD8Xsb7u5CnL83yYa85tN5V96c41xOxrSp_5VW4W5LeNuJAD2bDx-a2lVtTAMz34w',
          'secret' => '<my private key>',
          'remoteip' => '174.35.130.2'
        };
response: $VAR1 = {
          'success' => '',
          'protocol' => 'HTTP/1.1',
          'headers' => {
                         'cache-control' => 'private, max-age=0',
                         'transfer-encoding' => 'chunked',
                         'accept-ranges' => 'none',
                         'date' => 'Thu, 15 Jan 2015 22:15:57 GMT',
                         'vary' => 'Accept-Encoding',
                         'content-type' => 'text/html; charset=UTF-8',
                         'x-xss-protection' => '1; mode=block',
                         'x-content-type-options' => 'nosniff',
                         'server' => 'GSE',
                         'expires' => 'Thu, 15 Jan 2015 22:15:57 GMT',
                         'alternate-protocol' => '80:quic,p=0.02'
                       },
          'status' => '403',
          'url' => 'http://www.google.com/recaptcha/api/siteverify',
          'content' => '<HTML>
<HEAD>
<TITLE>Forbidden</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Forbidden</H1>

<H2>Error 403</H2>

</BODY>
</HTML>
',
          'reason' => 'Forbidden'
        };

**Comment by clarson** [comment]
Yep, I'll work on exposing more.  The only thing that is available today is that there is 3 possible return values.  0, 1, and nothing (undef).  It would be interesting if you could find out if it is returning 0 or undef to see if it is a flat out failure or an "input" error.

I'll see what I can come up with tonight to give more information on the response from google, so you have something in the morning.

Thanks,
Chuck
.

**Comment by clarson** [comment]
Version v0.09 has been uploaded to CPAN, works the same way has before, but a new methods named errors was added that will allow you to get more informations regarding why a failure happened.

Thanks,
Chuck

**Comment by clewisgithub** [comment]
On 01/15/2015 06:48 PM, Chuck Larson wrote:

> Closed #2 https://github.com/clarson/Captcha-noCAPTCHA/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clarson/Captcha-noCAPTCHA/issues/2#event-219792892.

Thanks Chuck,

I think what's happening is that Google is 403'ing non-SSL.  I was
failing on SSL because I didn't have a recent enough IO::Socket::SSL and
it was outright bletching.  I've updated IO::Socket::SSL, and it seems
to work now.

I can fiddle around with the updated noCAPTCHA and see if I have any
suggestions for getting transport-related errors visible in a useable way.

Oh the horrors of taking over a production machine umpty-ump years out
of up-to-date, and you're afraid to update anything for fear of breaking
the whole installation.
